'use client';
import {useState,useEffect} from 'react';
import {ArrowUpRight,ArrowRight,Check,Users,ScanLine,Sparkles,Network,ChevronDown,LoaderCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Progress} from '@/components/ui/progress';
import {people,examples,type Person} from '@/lib/people';
type Match={id:string;fit:string;relation:string;why:string;talk:string;gap:string;refs:{field:'intro'|'needs';quote:string}[];person:Person};
type Result={matches:Match[];rejected:{id:string;name:string;why:string;gap:string}[];plan:{summary:string;needs:string[]};stats:{pool:number;reviewed:number;shown:number;calls:number;seconds:number;model:string};prepared?:boolean};
const stages=['理解你的背景與意圖','語意與文字檢索','取得候選線索','核對雙方關係與證據','整理有價值的交流起點'];
export default function Home(){
 const [background,setBackground]=useState(examples[0].background),[query,setQuery]=useState(examples[0].query);
 const [step,setStep]=useState(-1),[busy,setBusy]=useState(false),[detail,setDetail]=useState('每次推薦，都能回到資料裡看依據。');
 const [plan,setPlan]=useState<{summary:string;needs:string[]}|null>(null),[result,setResult]=useState<Result|null>(null),[error,setError]=useState('');
 const [candidates,setCandidates]=useState<{id:string;name:string;focus:string}[]>([]),[checked,setChecked]=useState(0),[elapsed,setElapsed]=useState(0);
 const [showPool,setShowPool]=useState(false),[mode,setMode]=useState<'own'|'participant'>('participant'),[selected,setSelected]=useState(''),[prepared,setPrepared]=useState<Record<string,Result>>({});
 useEffect(()=>{fetch('/data/precomputed.json').then(async r=>(r.ok?await r.json():{}) as {results?:Record<string,Result>}).then(d=>{const entries=d.results||{};setPrepared(entries);const id=Object.keys(entries)[0];if(id){setSelected(id);const p=people.find(p=>p.id===id);if(p){setBackground(p.intro);setQuery(p.needs);}setResult(entries[id]);setPlan(entries[id].plan);setStep(5);setDetail('預先配對已完成；本次讀取沒有呼叫模型。');}}).catch(()=>{});},[]);
 useEffect(()=>{if(!busy)return;const start=Date.now();const timer=setInterval(()=>setElapsed(Math.floor((Date.now()-start)/1000)),500);return()=>clearInterval(timer);},[busy]);
 function clear(){setResult(null);setError('');setPlan(null);setStep(-1);setCandidates([]);setChecked(0);setDetail('每次推薦，都能回到資料裡看依據。');}
 function selectPerson(id:string){clear();setSelected(id);const p=people.find(p=>p.id===id);if(!p)return;setBackground(p.intro);setQuery(p.needs||'我適合認識誰？');if(prepared[id]){setResult(prepared[id]);setPlan(prepared[id].plan);setStep(5);setDetail('已讀取這位參加者的預先配對。本次沒有呼叫模型。');}}
 async function run(){if(!background.trim()||!query.trim())return;clear();setBusy(true);setElapsed(0);
  try{const r=await fetch('/api/match',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({background,query,viewerId:mode==='participant'?selected:undefined})});if(!r.ok){const e=await r.json() as {error?:string};throw Error(e.error||'暫時無法執行');}const reader=r.body!.getReader();const decoder=new TextDecoder();let buffer='';let completed=false;
   while(true){const item=await reader.read();if(item.done)break;buffer+=decoder.decode(item.value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()!;for(const line of lines){if(!line.trim())continue;const e=JSON.parse(line);if(e.step!==undefined)setStep(e.step);if(e.detail)setDetail(e.detail);if(e.type==='plan')setPlan(e.plan);if(e.type==='retrieval')setCandidates(e.candidates);if(e.type==='checked')setChecked(e.done);if(e.type==='error')throw Error(e.message);if(e.type==='result'){setResult(e);setStep(5);setDetail('完成來源核對。看看你們為什麼值得聊聊。');completed=true;}}}
   if(!completed)throw Error('連線結束前未取得完整結果，請重試。');
  }catch(e){setError(e instanceof Error?e.message:'連線中斷，請重試。');}finally{setBusy(false);}}
 return <div className="app-shell"><header className="topbar"><a href="/" className="brand"><span className="brand-symbol">b<span>•</span></span><span>BOBA TECH<span className="brand-sub"> / CONNECT</span></span></a><nav><button onClick={()=>setShowPool(!showPool)}><Users size={15}/>匿名名錄 <span className="count">{people.length}</span></button><a href="/architecture">技術說明 <ArrowUpRight size={14}/></a><span className="event-pill">BUILDMODE 2026</span></nav></header>
 <section className="hero"><div><div className="eyebrow"><span className="live-dot"/> FROM STRANGERS TO CONVERSATIONS</div><h1>人很多。<span>從對的人開始。</span></h1><p>認識誰、為什麼值得聊、可以怎麼開場。讓每一次相遇，都有一個起點。</p></div><div className="hero-note"><Network size={26}/><span>背景 × 需求 × 交流價值</span></div></section>
 <main className="workspace"><section className="platform-column"><div className="column-heading"><span className="eyebrow">BOBA TECH / DEMO PLATFORM</span><span className="small-badge">匿名化示範副本</span></div><section className="input-panel panel"><div className="mode-switch"><Button variant={mode==='participant'?'default':'ghost'} disabled={busy} onClick={()=>{setMode('participant');clear();}}>參加者預先配對</Button><Button variant={mode==='own'?'default':'ghost'} disabled={busy} onClick={()=>{setMode('own');clear();}}>用我的資料試試</Button></div>
 {mode==='participant'&&<label className="field">選一位參加者，看看適合認識誰<select value={selected} disabled={busy} onChange={e=>selectPerson(e.target.value)}><option value="">選擇匿名化參加者</option>{people.map(p=><option key={p.id} value={p.id}>{p.name} · {p.role}{prepared[p.id]?' · 配對已備妥':''}</option>)}</select><small>{Object.keys(prepared).length} / {people.length} 位已有預先配對；也能修改需求，重新即時搜尋。</small></label>}
 <div className="input-grid"><label className="field">我的背景<Textarea value={background} maxLength={2200} disabled={busy} onChange={e=>{setBackground(e.target.value);clear();}} placeholder="你在做什麼？有哪些經驗？" rows={4}/></label><label className="field">這次想認識的人<Textarea value={query} maxLength={1000} disabled={busy} onChange={e=>{setQuery(e.target.value);clear();}} placeholder="具體需求，或問：誰適合我認識？" rows={4}/></label></div>
 <Button className="find-button" onClick={run} disabled={busy||!background.trim()||!query.trim()}>{busy?<><LoaderCircle className="spin" size={18}/>正在尋找交流起點</>:<>即時幫我找到對的人<ArrowRight size={18}/></>}</Button><p className="privacy-note">送出後由 OpenAI 處理背景與需求，不加入公開名單。請勿輸入聯絡方式或敏感資訊。</p><div className="examples">{examples.map((e,i)=><button key={i} disabled={busy} onClick={()=>{setMode('own');setBackground(e.background);setQuery(e.query);clear();}}>{e.label}<ArrowUpRight size={12}/></button>)}</div></section>
 <section className="results-panel"><div className="results-heading"><h2>{result?'這幾個人，值得開始聊聊':'你的下一場對話'}</h2>{result&&<span>{result.matches.length} 位推薦</span>}</div>
 {!result?<div className="empty-state"><div className="connection-art"><span className="art-person a">你</span><i/><span className="art-person b">?</span><span className="art-person c">?</span><span className="art-person d">?</span></div><h3>{busy?'正在找出你們的具體連結':'不只找到名字，還知道為何值得聊。'}</h3><p>{busy?'結果會在來源核對完成後出現。':'選一位參加者查看預先配對，或填入自己的背景試試。'}</p></div>:<><p className="result-scope">{result.prepared?'已預先計算 · ':''}{result.stats.pool} 人名單中，本次檢視 {result.stats.reviewed} 位候選。未入選不代表不適合。</p>
 {!result.matches.length&&<div className="empty-state"><h3>本次沒有足夠證據支持推薦</h3><p>可以補充交流方向，或瀏覽完整示範名單。</p></div>}
 {result.matches.map((m,i)=><article className="match-card" key={m.id}><div className="person-row"><div className="avatar">{m.person.name.replace('參加者','').trim().slice(0,3)}</div><div><h3>{m.person.name}</h3><p>{m.person.role} · {m.person.focus}</p></div><span className="match-index">0{i+1}</span></div><div className="relation-tag">{m.relation}<span>{m.fit==='possible'?'探索線索':'具體交流方向'}</span></div><p className="why">{m.why}</p><div className="conversation"><span>可以從這句話開始</span><p>「{m.talk}」</p></div><details><summary>查看配對依據 <ChevronDown size={14}/></summary>{m.refs.map((ref,j)=><div className="source" key={j}><small>{ref.field==='intro'?'對方背景':'對方需求'} · 匿名化摘要</small><blockquote>{ref.quote}</blockquote></div>)}<p className="gap">待確認：{m.gap||'實際意願與時程需由雙方確認。'}</p><div className="full-profile"><b>完整示範背景</b><p>{m.person.intro}</p><b>希望認識的對象</b><p>{m.person.needs}</p></div></details></article>)}
 {result.rejected?.length>0&&<details className="rejected"><summary>哪些線索沒有成立（{result.rejected.length}）</summary>{result.rejected.slice(0,5).map(r=><p key={r.id}><b>{r.name}</b>：{r.why} {r.gap}</p>)}</details>}</>}
 </section></section>
 <aside className="process-column"><div className="column-heading"><span className="eyebrow">AGENT / LIVE WORKSPACE</span><span className={busy?'live-badge':'small-badge'}>{busy?'LIVE · 執行中':result?.prepared?'預先配對紀錄':'即時流程'}</span></div><section className="process-panel panel"><div className="panel-label"><span>看見配對如何發生</span><ScanLine size={19}/></div><p className="subtle">執行狀態、Agent 判定摘要與來源驗證。<br/>點開推薦卡片，可查看理由、引用與待確認事項。</p>{busy&&<div className="agent-flow" aria-label="即時執行流程"><span className={step===0?'flow-active':''}>你的需求</span><svg viewBox="0 0 80 20" aria-hidden="true"><path className={step===1?'flow-moving':''} d="M0 10 H80"/></svg><span className={step===1?'flow-active':''}>Embedding</span><svg viewBox="0 0 80 20" aria-hidden="true"><path className={step>=2?'flow-moving':''} d="M0 10 H80"/></svg><span className={step===3?'flow-active':''}>{candidates.length||20} 位候選<br/>Agent 核對</span></div>}<ol className="timeline">{stages.map((s,i)=><li key={s} className={step>i?'done':step===i?'active':''}><span className="step-marker">{step>i?<Check size={16}/>:i+1}</span><div><strong>{s}</strong>{step===i&&<p>{detail}</p>}{step>i&&i===0&&plan&&<p>{plan.summary}</p>}{step>i&&i===1&&<p>語意向量與文字排名融合</p>}{step>i&&i===2&&<p>{result?.stats.reviewed||candidates.length} 位候選，交由來源判讀</p>}{i===3&&step>=3&&<p>{result?result.stats.shown:checked} {result?'位推薦的引文已驗證':`/ ${candidates.length} 位已核對`}</p>}{i===4&&step>4&&<p>{detail}</p>}</div></li>)}</ol>
 {busy&&<div className="running-status"><Progress value={Math.min(95,Math.max(5,step*18+checked/2))}/><span>已等候 {elapsed} 秒 · 依 API 實際速度更新</span></div>}
 {plan&&<div className="intent-box"><span className="mini-label">這次的交流方向</span>{plan.needs.map((n,i)=><p key={i}><span>↗</span>{n}</p>)}</div>}
 {candidates.length>0&&<div className="candidate-cloud"><span className="mini-label">檢索取得的候選</span><div>{candidates.map(p=><span key={p.id}>{p.name}</span>)}</div></div>}
 {result&&<div className="receipt"><span className="live-dot"/>{result.prepared?'已保存的配對 · 本次零模型呼叫':`本次 ${result.stats.seconds} 秒 · ${result.stats.calls} 次 API 呼叫`}<small>{result.stats.model} · 來源引文逐字檢查</small></div>}{error&&<div role="alert" className="error-box">{error}</div>}
 <div className="why-not-search"><Sparkles size={17}/><div><strong>相似，只是開始。</strong><p>系統接著核對「你的處境 × 對方的經驗」，產生可實際開始的對話。</p></div></div></section></aside></main>
 {showPool&&<section className="pool-section"><div className="section-title"><div><span className="eyebrow">THE PEOPLE BEHIND THE MATCH</span><h2>完整匿名化示範名單</h2></div><Button variant="outline" onClick={()=>setShowPool(false)}>收起名單</Button></div><p className="subtle">這是概括改寫的示範副本，不包含公開身分對照。配對引用核對的是這份摘要，不是本人逐字原話。</p><div className="pool-grid">{people.map(p=><article key={p.id}><small>{p.id} / {p.focus}</small><h3>{p.name} · {p.role}</h3><p>{p.intro}</p><strong>想認識的人</strong><p>{p.needs}</p><Button variant="outline" disabled={busy} onClick={()=>{setMode('participant');selectPerson(p.id);window.scrollTo({top:180,behavior:'smooth'});}}>查看配對<ArrowUpRight size={14}/></Button></article>)}</div></section>}
 <footer><span>BOBA TECH / CONNECT · BUILDMODE 2026</span><span>把陌生人，變成一場有理由開始的對話。</span><a href="/architecture">架構與資料說明 ↗</a></footer></div>
}
