import fs from 'node:fs';
import {shortlist,validateDecisions,rankCandidates,JUDGE_PROMPT} from '../lib/engine.ts';
const people=JSON.parse(fs.readFileSync('lib/generated-people.json','utf8'));const model=process.env.OPENAI_MODEL||'gpt-5-mini';
fs.mkdirSync('work/precompute',{recursive:true});fs.mkdirSync('public/data',{recursive:true});
async function api(path,body){for(let retry=0;;retry++){const r=await fetch('https://api.openai.com/v1/'+path,{method:'POST',headers:{Authorization:'Bearer '+process.env.OPENAI_API_KEY,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(130000)});if((r.status===429||r.status>=500)&&retry<3){await new Promise(x=>setTimeout(x,4000*(retry+1)));continue;}if(!r.ok)throw Error('HTTP '+r.status);return r.json();}}
const vectorFile='work/precompute/vectors.json';let vectors;
if(fs.existsSync(vectorFile))vectors=JSON.parse(fs.readFileSync(vectorFile,'utf8'));else{const r=await api('embeddings',{model:'text-embedding-3-small',dimensions:512,input:people.map(p=>p.intro+'\n'+p.needs)});vectors=r.data.sort((a,b)=>a.index-b.index).map(x=>x.embedding);fs.writeFileSync(vectorFile,JSON.stringify(vectors));}
const str={type:'string'};const schema={type:'object',additionalProperties:false,properties:{matches:{type:'array',maxItems:5,items:{type:'object',additionalProperties:false,properties:{id:str,fit:{type:'string',enum:['strong','possible']},relation:str,why:str,talk:str,gap:str,score:{type:'integer',minimum:0,maximum:100},refs:{type:'array',items:{type:'object',additionalProperties:false,properties:{field:{type:'string',enum:['intro','needs']},quote:str},required:['field','quote']}}},required:['id','fit','relation','why','talk','gap','score','refs']}}},required:['matches']};
let next=0,failed=0;const results={};
function save(){const payload={version:'boba-demo-precompute.v1',dataset:'anonymous-172',total:people.length,completed:Object.keys(results).length,failed,results};fs.writeFileSync('public/data/precomputed.next.json',JSON.stringify(payload));fs.copyFileSync('public/data/precomputed.next.json','public/data/precomputed.json');}
async function worker(){while(next<people.length){const i=next++;const seeker=people[i];const file=`work/precompute/${seeker.id}.json`;try{if(fs.existsSync(file)){results[seeker.id]=JSON.parse(fs.readFileSync(file,'utf8'));save();continue;}const started=Date.now();const pool=people.filter(p=>p.id!==seeker.id);const vec=vectors.filter((_,n)=>n!==i);const ranked=shortlist(pool,vec,vectors[i],seeker.intro+' '+seeker.needs);const candidates=ranked.map(x=>x.person);let checked;let previous;let citationError;let calls=0;
for(let attempt=0;attempt<3;attempt++){calls++;const r=await api('responses',{model,store:false,reasoning:{effort:'low'},instructions:JUDGE_PROMPT.replace('Assess every supplied ID exactly once.','Select up to FIVE best candidates from the supplied pool. Empty matches is valid. Return only selected candidates; do not claim that missing candidates are unqualified.')+' Prefer a diverse useful shortlist over five near-identical reasons. Keep why under 100 Chinese characters, talk under 45, gaps under 35, and use short exact quotes.',input:JSON.stringify({seeker:{background:seeker.intro,query:seeker.needs||'適合認識誰'},candidates,previous,citationError}),text:{format:{type:'json_schema',name:'prepared_matches',strict:true,schema}},max_output_tokens:6000});if(r.status!=='completed')throw Error('Incomplete model output');const raw=JSON.parse(r.output.flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('')).matches;try{checked=validateDecisions(raw,candidates.filter(p=>raw.some(m=>m.id===p.id)));break;}catch(e){previous=raw;citationError=e.message+" Copy a SHORT contiguous substring EXACTLY from this candidate intro or needs. Do not paraphrase quotes.";if(attempt===2)throw e;}}
const matches=rankCandidates(checked,5).map(d=>({...d,score:undefined,person:people.find(p=>p.id===d.id)}));const result={prepared:true,matches,rejected:[],plan:{summary:'根據這位參加者的匿名化背景與需求，探索有具體交流連結的人。',needs:[seeker.needs]},stats:{pool:people.length,reviewed:candidates.length,shown:matches.length,calls,seconds:Math.round((Date.now()-started)/100)/10,model},createdAt:new Date().toISOString()};fs.writeFileSync(file,JSON.stringify(result));results[seeker.id]=result;save();console.log(JSON.stringify({completed:Object.keys(results).length,total:people.length,id:seeker.id,matches:matches.length}));
}catch(e){failed++;console.log(JSON.stringify({id:seeker.id,error:e.message}));save();}}}
await Promise.all(Array.from({length:8},()=>worker()));save();console.log(JSON.stringify({complete:Object.keys(results).length,total:people.length,failed}));
